// <auto-generated/>
using System.Text.Json.Serialization;

namespace TwitchRoboLlamaPlugin;

public partial class GameDataResponse
{
    [JsonPropertyName("data")]
    public List<GameData> Data { get; set; }
}

public partial class GameData
{
    [JsonPropertyName("box_art_url")]
    public Uri BoxArtUrl { get; set; }

    [JsonPropertyName("id")]

    public string Id { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }
}
