// <auto-generated/>
using Dapper.Contrib.Extensions;

namespace TwitchRoboLlamaPlugin;

[Table("Subscriptions")]
public class Subscription
{
    [Key] public int Id { get; set; }

    public string ChannelId { get; set; }

    public string ChannelName { get; set; }

    public DateTime? RegistryDate { get; set; }

    public bool Announced { get; set; }
    public string SubscriptionId { get; set; }
    public string UpdateId { get; set; }
}