// <auto-generated/>
using Dapper.Contrib.Extensions;

namespace TwitchRoboLlamaPlugin;

[Table("TwitchStreamAlerts")]
public class TwitchStreamAlert
{
    [Key] public int Id { get; set; }

    public string UserName { get; set; }

    public string Title { get; set; }

    public int ViewerCount { get; set; }

    public string GameId { get; set; }

    public string ChannelId { get; set; }

    public bool Announced { get; set; }
}