// <auto-generated />
using System.Text.Json.Serialization;

namespace TwitchRoboLlamaPlugin;

public class TwitchSubscription
{
	[JsonPropertyName("id")]
	public string Id { get; set; }

	[JsonPropertyName("type")]
	public string Type { get; set; }

	[JsonPropertyName("version")]
	public string Version { get; set; }

	[JsonPropertyName("status")]
	public string Status { get; set; }

	[JsonPropertyName("cost")]
	public long Cost { get; set; }

	[JsonPropertyName("condition")]
	public Condition Condition { get; set; }

	[JsonPropertyName("transport")]
	public Transport Transport { get; set; }

	[JsonPropertyName("created_at")]
	public DateTimeOffset CreatedAt { get; set; }
}

public class Condition
{
	[JsonPropertyName("broadcaster_user_id")]
	public string BroadcasterUserId { get; set; }
}

public class Transport
{
	[JsonPropertyName("method")]
	public string Method { get; set; }

	[JsonPropertyName("callback")]
	public Uri Callback { get; set; }
}
