// <auto-generated/>
namespace RoboLlama.Models;

public class ServerConfig
{
    public const string Key = "ServerConfig";
    public string ServerAddress { get; set; }
    public int ServerPort { get; set; }
    public string Owner { get; set; }
    public string NickPass { get; set; }
    public string[] Channels { get; set; }
    public string[] Nicks { get; set; }
    public string AdminNick { get; set; }
    public string PluginFolder { get; set; }
    public string Root { get; set; }
}
