// <auto-generated/>

using System.Text.Json.Serialization;

namespace TwitterRoboLlamaPlugin;

public class TwitterResponse
{
    public Datum[] data { get; set; }
}

public class Datum
{
    public string id { get; set; }
    public string text { get; set; }
}