// <auto-generated/>
using System.Text.Json.Serialization;

namespace TwitterRoboLlamaPlugin;

public class TwitterAuthenticateResponse
{
    [JsonPropertyName("token_type")] public string TokenType { get; set; }

    [JsonPropertyName("access_token")] public string AccessToken { get; set; }
}